sm7325-common: Nuke some unused 32bit blobs
error: vendor/motorola/sm7325-common/Android.bp:2166:1: dependency "libQSEEComAPI" of "libcvp_util" missing variant:
  os:android,image:vendor,arch:arm_armv8-a,sdk:,link:shared
Change-Id: I55e74a8d4b9c753849dc6faab24e84d8190e0823